name: PR Checks Github Action
on: pull_request
jobs:
  lint:
    name: Lint check
    runs-on: [ubuntu-latest]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@89f242ee29e10c53a841bfe71cc0ce7b2f065abc
        with:
          access_token: ${{ github.token }}
      - name: Cleanup workspace
        uses: AutoModality/action-clean@d004b47eb728f2a83316fc70ba9a62ef97278013
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Setup credentials
        run: |
          touch local.properties
          echo "omdb_api_key=${{ secrets.OMDB_API_KEY }}" >> local.properties
      - name: Setup Android env
        uses: ./.github/actions/setup-android-env
      - name: Run lint
        run: ./gradlew clean lintDebug
  tests:
    name: Unit tests
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@89f242ee29e10c53a841bfe71cc0ce7b2f065abc
        with:
          access_token: ${{ github.token }}
      - name: Cleanup workspace
        uses: AutoModality/action-clean@d004b47eb728f2a83316fc70ba9a62ef97278013
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Setup Android env
        uses: ./.github/actions/setup-android-env
      - name: Setup credentials
        run: |
          touch local.properties
          echo "omdb_api_key=${{ secrets.OMDB_API_KEY }}" >> local.properties
      - name: Run unit tests
        run: ./gradlew clean testDebugUnitTest
